version: '3.9'
services:
  proxy:
    volumes:
      - '/opt/cache:/opt/cache'
      - '/opt/keys:/opt/keys'
      - '/opt/db:/opt/db'
    environment:
      - KPROXY_PATH=/opt/cache
      - KPROXY_DB_PATH=/opt/db
      - KPROXY_CERT=/opt/keys/kproxy-ca.pem
      - KPROXY_KEY=/opt/keys/kproxy-ca.key
    ports:
      - '8080:8080'
      - '8081:8081'
    restart: always
    build: .
    entrypoint: go run main.go -port=8080 -config -config-port=8081
